version: 0.0
os: linux
files:
  - source: /
    destination: /home/ubuntu/api
hooks:
  ApplicationStop:
    - location: scripts/application_stop.sh
      timeout: 15
      runas: root
  ValidateService:
    - location: scripts/application_start.sh
      timeout: 15
      runas: root